version: "3"

services:
  db:
    container_name: count-money-mongo
    image: mongo
    restart: always
    command: mongod --auth
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${MONGO_INITDB_DATABASE} --quiet
      start_period: 15s
      retries: 3
      interval: 15s
    ports:
      - 27017:27017
    networks:
      - back-tier
    volumes:
      - db-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  api:
    build:
      context: ./api
    container_name: count-money-api
    restart: always
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      SECRET_HASH: ${SECRET_HASH}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      DB_NAME: ${MONGO_INITDB_DATABASE}
      DB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${DB_HOST}:${DB_PORT}/${MONGO_INITDB_DATABASE}
      COINRANKING_KEY: ${COINRANKING_KEY}
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      GOOGLE_AUTH_URI: ${GOOGLE_AUTH_URI}
      GOOGLE_TOKEN_URI: ${GOOGLE_TOKEN_URI}
      GOOGLE_AUTH_PROVIDER_X509_CERT_URL: ${GOOGLE_AUTH_PROVIDER_X509_CERT_URL}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${OAUTH_REDIRECT_URI}/oauth/google
      GOOGLE_USER_URI: ${GOOGLE_USER_URI}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_AUTH_URI: ${GITHUB_AUTH_URI}
      GITHUB_TOKEN_URI: ${GITHUB_TOKEN_URI}
      GITHUB_USER_URI: ${GITHUB_USER_URI}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    networks:
      - back-tier
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true
  web:
    build:
      context: ./web
    container_name: count-money-web
    restart: always
    environment:
      BACKEND_URL: count-money-api
      NODE_ENV: ${NODE_ENV}
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      GOOGLE_AUTH_URI: ${GOOGLE_AUTH_URI}
      GOOGLE_TOKEN_URI: ${GOOGLE_TOKEN_URI}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_AUTH_URI: ${GITHUB_AUTH_URI}
    ports:
      - 8080:8080
    depends_on:
      - api

networks:
  back-tier:
    name: ${NETWORK_BACK}

volumes:
  db-data:
    name: ${DATABASE_VOLUME}
